services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.api
    image: edkesuma/covidoc-fyp-api
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./server/instance
        target: /app/instance
    secrets:
      - gcp_service_account
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /run/secrets/gcp_service_account
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile.client
    image: edkesuma/covidoc-fyp-client
    ports:
      - "80:80"
  
secrets:
  gcp_service_account:
    file: ./server/servicekey_googlecloud.json