{
    "metadata_path": "/kaggle/input/covid-x-ray-dataset/balanced/metadata.csv",
    "image_folder": "/kaggle/input/covid-x-ray-dataset/balanced",
    "image_dimensions": [224,224],
    "max_epochs": 30,
    "project_name": "fyp-covidnext50",
    "run_name": "resnext50_224x224",
    "patience": 5,
    "train_severity": False
}