{
    "metadata_path": "/kaggle/input/covid-x-ray-severity-dataset/data_sev/metadata.csv",
    "image_folder": "/kaggle/input/covid-x-ray-severity-dataset/data_sev",
    "image_dimensions": [224,224],
    "max_epochs": 70,
    "project_name": "fyp-covidnext50-severity",
    "run_name": "resnext50_224x224",
    "patience": 10,
    "train_severity": True
}